import React, { useState, useEffect } from 'react';
import { fetchAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { Activity, RefreshCw, Send, CheckCircle2, AlertTriangle, Filter, Terminal, Zap } from 'lucide-react';

export const SecurityEvents = () => {
  const [events, setEvents] = useState([]);
  const [filterType, setFilterType] = useState('ALL');
  const [loading, setLoading] = useState(true);
  const [simulating, setSimulating] = useState(false);
  const { showToast } = useAuth();

  const loadEvents = async () => {
    setLoading(true);
    try {
      const data = await fetchAPI('/security/events?limit=100');
      setEvents(data);
    } catch (err) {
      showToast('Failed to load security events: ' + err.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadEvents();
    const interval = setInterval(loadEvents, 4000);
    return () => clearInterval(interval);
  }, []);

  const handleSimulateBruteForce = async () => {
    setSimulating(true);
    try {
      await fetchAPI('/security/simulate-bruteforce', {
        method: 'POST',
        body: JSON.stringify({ username: 'admin' })
      });
      showToast('⚡ Fired 5x LOGIN_FAILED events to ZentraSec API!', 'warning');
      loadEvents();
    } catch (err) {
      showToast(err.message, 'error');
    } finally {
      setSimulating(false);
    }
  };

  const handleManualEvent = async (eventType) => {
    try {
      await fetchAPI('/security/manual-event', {
        method: 'POST',
        body: JSON.stringify({
          event_type: eventType,
          username: 'demo_user',
          user_role: 'teacher',
          resource: '/manual-simulation',
          metadata: { demo_mode: true, timestamp: new Date().toISOString() }
        })
      });
      showToast(`Event '${eventType}' sent to ZentraSec!`, 'success');
      loadEvents();
    } catch (err) {
      showToast(err.message, 'error');
    }
  };

  const filteredEvents = events.filter(e => filterType === 'ALL' || e.event_type === filterType);

  const eventTypes = [
    'ALL',
    'LOGIN_SUCCESS',
    'LOGIN_FAILED',
    'LOGOUT',
    'STUDENT_CREATED',
    'STUDENT_UPDATED',
    'STUDENT_DELETED',
    'ATTENDANCE_MODIFIED',
    'RESULT_MODIFIED',
    'RESULT_DELETED',
    'UNAUTHORIZED_ACCESS',
    'ADMIN_ACTION'
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Banner */}
      <div className="glass-card">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <Activity size={24} color="var(--accent-cyan)" />
            <div>
              <h3 style={{ fontSize: '1.25rem', fontWeight: '800', color: '#fff' }}>Security Telemetry Monitor</h3>
              <p style={{ fontSize: '0.8125rem', color: 'var(--text-muted)' }}>
                Live feed of all security events generated by the School Portal and sent via HTTP POST to ZentraSec Threat Engine.
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <button onClick={loadEvents} className="btn btn-secondary btn-sm">
              <RefreshCw size={14} className={loading ? 'spin' : ''} />
              <span>Refresh Feed</span>
            </button>
          </div>
        </div>
      </div>

      {/* Instant Event Generator Toolbar */}
      <div className="glass-card" style={{ padding: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.75rem' }}>
          <Zap size={18} color="var(--accent-amber)" />
          <span style={{ fontSize: '0.875rem', fontWeight: '700', color: '#fff' }}>Quick Telemetry Simulators for Demo</span>
        </div>
        <div style={{ display: 'flex', gap: '0.65rem', flexWrap: 'wrap' }}>
          <button onClick={handleSimulateBruteForce} disabled={simulating} className="btn btn-danger btn-sm">
            🚨 5x Brute Force (LOGIN_FAILED)
          </button>
          <button onClick={() => handleManualEvent('UNAUTHORIZED_ACCESS')} className="btn btn-secondary btn-sm">
            🔒 UNAUTHORIZED_ACCESS
          </button>
          <button onClick={() => handleManualEvent('RESULT_MODIFIED')} className="btn btn-secondary btn-sm">
            📝 RESULT_MODIFIED
          </button>
          <button onClick={() => handleManualEvent('STUDENT_DELETED')} className="btn btn-secondary btn-sm">
            🗑️ STUDENT_DELETED
          </button>
          <button onClick={() => handleManualEvent('ATTENDANCE_MODIFIED')} className="btn btn-secondary btn-sm">
            📅 ATTENDANCE_MODIFIED
          </button>
        </div>
      </div>

      {/* Filter Bar */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', overflowX: 'auto', paddingBottom: '0.25rem' }}>
        <Filter size={14} color="var(--text-muted)" />
        <span style={{ fontSize: '0.75rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Filter:</span>
        {eventTypes.map(t => (
          <button
            key={t}
            onClick={() => setFilterType(t)}
            className={`btn btn-sm ${filterType === t ? 'btn-primary' : 'btn-secondary'}`}
            style={{ padding: '0.25rem 0.65rem', fontSize: '0.75rem', fontFamily: 'var(--font-mono)' }}
          >
            {t}
          </button>
        ))}
      </div>

      {/* Telemetry Stream List */}
      <div className="glass-card" style={{ padding: 0, overflow: 'hidden' }}>
        <div className="table-responsive">
          <table className="custom-table">
            <thead>
              <tr>
                <th>Timestamp</th>
                <th>Event Type</th>
                <th>User / Role</th>
                <th>IP Address</th>
                <th>Resource Endpoint</th>
                <th>Delivery Status</th>
                <th>Payload Metadata</th>
              </tr>
            </thead>
            <tbody>
              {filteredEvents.length === 0 ? (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center', padding: '2.5rem', color: 'var(--text-muted)' }}>
                    No matching security events found.
                  </td>
                </tr>
              ) : (
                filteredEvents.map((ev) => {
                  const isAlert = ['LOGIN_FAILED', 'UNAUTHORIZED_ACCESS', 'RESULT_DELETED'].includes(ev.event_type);
                  const isSuccess = ev.delivery_status === 'SENT';

                  return (
                    <tr key={ev.event_id}>
                      <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                        {new Date(ev.timestamp).toLocaleTimeString()}
                      </td>
                      <td>
                        <span className={`event-pill ${isAlert ? 'event-pill-alert' : 'event-pill-success'}`}>
                          {ev.event_type}
                        </span>
                      </td>
                      <td style={{ fontSize: '0.8125rem' }}>
                        <span style={{ fontWeight: '700', color: '#fff' }}>{ev.username}</span>{' '}
                        <span style={{ color: 'var(--text-dim)' }}>({ev.user_role})</span>
                      </td>
                      <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', color: 'var(--accent-cyan)' }}>
                        {ev.ip_address}
                      </td>
                      <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem' }}>
                        {ev.resource}
                      </td>
                      <td>
                        <span className={`badge ${isSuccess ? 'badge-sent' : 'badge-local'}`}>
                          {isSuccess ? <><CheckCircle2 size={12} /> Sent to ZentraSec</> : <><AlertTriangle size={12} /> Saved Locally</>}
                        </span>
                      </td>
                      <td>
                        <details style={{ cursor: 'pointer' }}>
                          <summary style={{ fontSize: '0.7rem', color: 'var(--accent-cyan)', fontFamily: 'var(--font-mono)' }}>
                            View JSON
                          </summary>
                          <pre style={{
                            marginTop: '0.35rem',
                            padding: '0.5rem',
                            background: '#0b0f19',
                            borderRadius: '4px',
                            fontSize: '0.65rem',
                            fontFamily: 'var(--font-mono)',
                            color: '#a5f3fc',
                            maxWidth: '260px',
                            overflowX: 'auto'
                          }}>
                            {JSON.stringify(ev.metadata, null, 2)}
                          </pre>
                        </details>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
